### ISSUE TITLE
Implement `eth_syncing`

### ISSUE THREAD

**Issue by chetan-zilliqa** [Zilliqa/zq2#1243]
Implement the `eth_syncing` API. If it exists, add the `eth_subscrbe` version of this too.

Discuss in slack how to determine whether a node is syncing or not. I can think of a few options with different tradeoffs. Some research needed.

**Comment by JamesHinshelwood** [comment]
@chetan-zilliqa If its okay, I'll change this ticket to specify implement `eth_syncing` which should give us all this information. I believe there is also a websocket version which a command line client could use to get live updates on sync status.

**Comment by rrw-zilliqa** [comment]
@JamesHinshelwood  - naively:

 - we are syncing if highest_known_view > current_view
 - startingBlock - is the block number at the highest confirmed view when we last started syncing.
  - currentBlock is the block number at the highest confirmed view
  - highestBlock - is currentBlock + (highest_known_view - currentBlock.view)
  
Does that seem sane? If you'd prefer something else, let me know...

**Comment by JamesHinshelwood** [comment]
@rrw-zilliqa Yes, that sounds sane to me. I think its unavoidable that a malicious node could cause us to get confused about `highest_known_view` - We can't know the committee in which a supermajority would be required in order to trust a block, without knowing that block's parent, which obvious requires syncing :)
