### ISSUE TITLE
Validators ignore blocks less than their current view

### ISSUE THREAD

**Issue by JamesHinshelwood** [Zilliqa/zq2#1400]
Currently, if a validator times out and increments `self.view` it will then ignore any block proposals received which are before `self.view`. It is correct that we shouldn't try to vote on proposals which are before our `self.view`, but we should still store them in case the rest of the network chooses that block as the canonical chain. We can maintain a condition of ignoring proposals if they are less than `self.finalised_view`, since these are blocks which are definitely not canonical.

**Comment by rrw-zilliqa** [comment]
A natural way of doing this is to keep them in block_store's (upcoming!) block response cache, where all the other blocks which we don't recognise (yet) as being canonical sit.

**Comment by 86667** [comment]
Turns out that this issue fixes itself by re-requesting blocks which were previously rejected due to having views less than current. 

@rrw-zilliqa's [PR](https://github.com/Zilliqa/zq2/pull/1495) adding a block_cache provides a mechanism to resolve this inefficiency. I will pick this up again once it has been merged.
