### ISSUE TITLE
Checkpoints should contain the state of the previous block

### ISSUE THREAD

**Issue by JamesHinshelwood** [Zilliqa/zq2#1430]
Current a checkpoint at block `x` contains:
* Serialised block `x`
* Serialised block `x-1`
* The state trie at block `x` (pointed to by the state root hash in block `x`)

However, this results in a state that isn't able to answer some questions about block `x`, such as who the proposer was. This is because the consensus committee for block `x` is defined by the state at block `x-1`.

So instead, we should store the state trie at block `x-1` and when loading a checkpoint, replay block `x` to construct a state which includes both `x-1` and `x`.

**Comment by 86667** [comment]
Note for self:

This causes nodes spawned from checkpoints to fail if they do not receive new blocks before timeout: they will attempt to recall information about the previous view (`x-1`) and fail due to the state trie not existing.

**Comment by 86667** [comment]
More notes:

For a checkpoint at block `x` we must wait until `x` is finalised, which is when block `x+1` has been checked and is ready for execution. There is a brief period in-between `x` being finalied and `x+1` being executed in which we have access to the state trie for `x`.  

Therefore, in order to know the state trie for `x-1` we have to have stored it during the previous view, ie when block `x` had been checked and was ready for execution, but not yet executed. Options for doing this are:

- Store clone of state trie for `x-1` somewhere temporarily whilst we have it, fetch to include in checkpoint once `x` is finalised
- Begin building checkpoint with `x-1` and its state trie, then complete build once `x` is finalised. This requires defining an extra message similar to `InternalMessage::ExportBlockCheckpoint` and restructuring the checkpoint file

Another option could be to pass the author seperately and manually add the necessary data to the state trie - look into this.

We can do either of these but the added complexity makes me wonder whether its worth it. How important is knowing the author for the checkpointed block, we could simply display `miner` as `0x0000000000000000000000000000000000000000`.

Or, the simplest and fastest way to resolve this would be for a checkpoint `x`, use the current mechanism to take the checkpoint at `x-1`. We can reload with block `x-2`, `x-1` and the state trie at `x-1`. The node can then grab the real "checkpoint" block `x` from its peers.
