### ISSUE TITLE
Z2-Converter API Mainnet : GetMinimumGasPrice

### ISSUE THREAD

**Issue by chetan-zilliqa** [Zilliqa/zq2#1668]
### Issue Summary:
Calling `GetMinimumGasPrice` on the ZQ1 and ZQ2 has the following diff.
Here are the URLs for ZQ1 and ZQ2.
ZQ2 : http://34.124.218.159:4201/
ZQ1 : http://34.124.185.137:4201/
### Result:
**Missing keys:**
```
```
**Different Keys:**
```
Values that differ between ZQ2 and ZQ1:
  root['result']:
    ZQ2: 2000000016
    ZQ1: 2000000000

```
### Observations:
There is a slight difference in gas price.

###  Conclusion:
If the above differences are expected and align with the migration to ZQ2, no further action is required. However, if these differences are unexpected, they may indicate issues that must be addressed.

**Comment by DrZoltanFazekas** [comment]
ZQ2 uses an `eth_getPrice` of 4,761.9048 gwei which corresponds to `2,000,000,016 / 420`. Any ZQ1 apps that use a hardcoded 2,000,000,000 gas price must be adjusted otherwise I don't see any reason not to accept this difference. If a ZQ2 node (aka super archive node) is about to re-execute ZQ1 transactions at a later point, we can implement an exemption.

**Comment by maxconway** [comment]
Closing based on Zoltan's comment
