### ISSUE TITLE
Z2-Converter : GetSmartContractState does not return _evm_storage field when callled with evm contract.

### ISSUE THREAD

**Issue by chetan-zilliqa** [Zilliqa/zq2#1782]
If we call `GetSmartContractState` on evm contract. It doesn't return `_evm_storage` field but zq1 does return.

```
--- Viewing difference for GetSmartContractState (0xf42d1058f233329185A36B04B7f96105afa1adD2) ---

Keys present in ZQ1 but missing in ZQ2:
  root['result']['_evm_storage']



```

**Comment by JamesHinshelwood** [comment]
In my view, this is an internal implementation detail of ZQ1 that leaks out. If no one objects, let's not do this. This is important for this feature in particular, because some alternative state storage mechanisms we're considering optimise for single-key retrieval from contract storage and would be quite slow at returning a contract's whole state.
