### ISSUE TITLE
Limit response size of `GetSmartContract(Sub)State`

### ISSUE THREAD

**Issue by JamesHinshelwood** [Zilliqa/zq2#993]
Querying the state of large contracts on ZQ1 causes performance problems/crashes. Some contracts have a lot of state (~50 MiB).

Add configuration to limit the size of the response from these APIs. Default it to on at a sensible level (1 MiB?).

**Comment by rrw-zilliqa** [comment]
.. and remember to provide instructions on how to configure your zq2 node to disable the restriction :-)
we also probably want to implement functionality to allow you to work out what state should be queried by GetContractSubState() otherwise block explorers will need to understand Scilla to show you state, which might be more than I want to implement :-p

**Comment by JamesHinshelwood** [comment]
Consider this blocked by #919 for now since that change will fundamentally affect how Scilla contract storage is stored and thus how we can account for its size.
